name: deploy-project
on: 
    push:
        branches: 
            - master
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: appleboy/ssh-action@v1
              with: 
                host: ${{ secrets.MY_SERVER_HOST }} # 要部署的服务器的host
                username: ${{ secrets.MY_SERVER_USERNAME }}
                password: ${{ secrets.MY_SERVER_PWD }}
                script: |
                    cd /home/ubuntu/web_project/vue3/admin-api
                    git pull github master
                    pnpm install
                    pnpm run build
                    pm2 restart admin-api
                # 服务端之前启动项目的pm2的命令： pm2 start pnpm --name admin-api -- start:prod


